AWSTemplateFormatVersion: '2010-09-09'
Description: Create an EC2 instance in a private subnet using a Launch Template.

Parameters:
  VpcId:
    Description: The ID of the VPC where the EC2 instance will be created.
    Type: String
  SubnetId:
    Description: The ID of the private subnet where the EC2 instance will be created.
    Type: String
  InstanceType:
    Description: The EC2 instance type (e.g., t2.micro, t3.medium).
    Type: String
    Default: t2.micro
  KeyName:
    Description: The name of the EC2 KeyPair to enable SSH access to the instance.
    Type: AWS::EC2::KeyPair::KeyName
  SecurityGroupId:
    Description: The ID of the security group to attach to the EC2 instance.
    Type: String
  AMIId:
    Description: The ID of the AMI to use for the EC2 instance.
    Type: String

Resources:
  EC2LaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateData:
        ImageId: !Ref AMIId
        InstanceType: !Ref InstanceType
        KeyName: !Ref KeyName
        NetworkInterfaces:
          - AssociatePublicIpAddress: false
            DeviceIndex: 0
            SubnetId: !Ref SubnetId
            Groups:
              - !Ref SecurityGroupId
        TagSpecifications:
          - ResourceType: instance
            Tags:
              - Key: Name
                Value: EC2InstanceFromLaunchTemplate
      LaunchTemplateName: EC2PrivateSubnetTemplate

  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      LaunchTemplate:
        LaunchTemplateId: !Ref EC2LaunchTemplate
        Version: !GetAtt EC2LaunchTemplate.LatestVersionNumber

Outputs:
  LaunchTemplateId:
    Description: The ID of the created EC2 Launch Template.
    Value: !Ref EC2LaunchTemplate
  InstanceId:
    Description: The ID of the created EC2 instance.
    Value: !Ref EC2Instance
  PrivateIPAddress:
    Description: The private IP address of the EC2 instance.
    Value: !GetAtt EC2Instance.PrivateIp

# aws cloudformation create-stack --stack-name EC2WithLaunchTemplateStack --template-body file://ec2_launch_template.yaml --parameters ParameterKey=VpcId,ParameterValue=<your-vpc-id> ParameterKey=SubnetId,ParameterValue=<your-subnet-id> ParameterKey=InstanceType,ParameterValue=<your-instance-type> ParameterKey=KeyName,ParameterValue=<your-key-name> ParameterKey=SecurityGroupId,ParameterValue=<your-security-group-id> ParameterKey=AMIId,ParameterValue=<your-ami-id>
