AWSTemplateFormatVersion: '2010-09-09'
Description: 'CodeBuild project with GitHub Enterprise source and S3 artifacts'

Parameters:
  ComputeSize:
    Type: String
    Default: small
    AllowedValues:
      - small
      - medium
      - large
    Description: CodeBuild instance size (small/medium/large)

Mappings:
  ComputeTypeMap:
    small:
      type: BUILD_GENERAL1_SMALL
    medium:
      type: BUILD_GENERAL1_MEDIUM
    large:
      type: BUILD_GENERAL1_LARGE

  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: VPC ID for CodeBuild project

  SubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
    Description: List of subnet IDs for CodeBuild project

  GitHubEnterpriseToken:
    Type: String
    Default: /codebuild/github-enterprise-token
    Description: Parameter Store path for GitHub Enterprise token

Resources:
  CodeBuildServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSCodeBuildAdminAccess
      Policies:
        - PolicyName: CodeBuildVPCPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - ec2:CreateNetworkInterface
                  - ec2:DescribeNetworkInterfaces
                  - ec2:DeleteNetworkInterface
                Resource: '*'
        - PolicyName: CodeBuildParameterStorePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - ssm:GetParameters
                Resource: !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter${GitHubEnterpriseToken}

  CodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Sub ${AWS::StackName}-project
      ServiceRole: !GetAtt CodeBuildServiceRole.Arn
      Artifacts:
        Type: S3
        Location: !Sub codebuild-${AWS::AccountId}-${AWS::Region}
        Path: build-project
        NamespaceType: BUILD_ID
        Packaging: ZIP
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: !FindInMap [ComputeTypeMap, !Ref ComputeSize, type]
        Image: aws/codebuild/amazonlinux2-x86_64-standard:4.0
      Source:
        Type: GITHUB_ENTERPRISE
        Location: https://github.enterprise.com/org/repo
        Auth:
          Type: OAUTH
          Resource: !Sub {{resolve:ssm:${GitHubEnterpriseToken}:1}}
      VpcConfig:
        VpcId: !Ref VpcId
        Subnets: !Ref SubnetIds
        SecurityGroupIds:
          - !Ref CodeBuildSecurityGroup

  CodeBuildSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for CodeBuild project
      VpcId: !Ref VpcId
      SecurityGroupEgress:
        - IpProtocol: -1
          FromPort: -1
          ToPort: -1
          CidrIp: 0.0.0.0/0

Outputs:
  ProjectName:
    Description: CodeBuild project name
    Value: !Ref CodeBuildProject
  ProjectArn:
    Description: CodeBuild project ARN
    Value: !GetAtt CodeBuildProject.Arn
    