Resources:
  SendMessageFunction:
    Type: AWS::Serverless::Function
    Properties: 
      Handler: send-message.lambda-function
      Runtime: python3.9
      CodeUri: ./send-message/
      Policies:
        - Statement:
            Effect: Allow
            Action:
              - "execute-api:ManageConnections"
            Resource: 
              - !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:<YOUR_API_ID>/*/@connections/*"
        - Statement:
            Effect: Allow
            Action:
              - "dynamodb:GetItem"
            Resource: 
              - !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/WebSocketConnections"
      Environment:
        Variables:
          WEBSOCKET_API_URL: !Sub "https://${ApiGatewayWebSocketApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
          DYNAMODB_TABLE_NAME: WebSocketConnections
