AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SAM template for Cognito User Pool setup with client credentials flow

Parameters:
  UserPoolName:
    Type: String
    Default: MyUserPool
    Description: Name of the Cognito User Pool
  DomainPrefix:
    Type: String
    Default: my-auth-domain
    Description: Prefix for Cognito domain name

Resources:
  CognitoUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Ref UserPoolName
      AdminCreateUserConfig:
        AllowAdminCreateUserOnly: true
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: true
          RequireUppercase: true

  UserPoolDomain:
    Type: AWS::Cognito::UserPoolDomain
    Properties:
      Domain: !Ref DomainPrefix
      UserPoolId: !Ref CognitoUserPool

  UserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      UserPoolId: !Ref CognitoUserPool
      ClientName: app-client
      GenerateSecret: true
      ExplicitAuthFlows: []  # Empty as we're only using OAuth flows
      AllowedOAuthFlows:
        - client_credentials
      AllowedOAuthScopes:
        - custom-scope/read    # Custom scope for API access
        - custom-scope/write   # Custom scope for API access
      AllowedOAuthFlowsUserPoolClient: true
      PreventUserExistenceErrors: ENABLED

  # Resource server to define custom scopes
  UserPoolResourceServer:
    Type: AWS::Cognito::UserPoolResourceServer
    Properties:
      UserPoolId: !Ref CognitoUserPool
      Identifier: "https://api.example.com"  # Can be any unique identifier
      Name: "MyAPIServer"
      Scopes: 
        - ScopeName: read
          ScopeDescription: "Read access to API"
        - ScopeName: write
          ScopeDescription: "Write access to API"

Outputs:
  UserPoolId:
    Description: ID of the Cognito User Pool
    Value: !Ref CognitoUserPool
  UserPoolClientId:
    Description: ID of the Cognito User Pool Client
    Value: !Ref UserPoolClient
  UserPoolDomainName:
    Description: Domain name for the Cognito User Pool
    Value: !Sub ${DomainPrefix}.auth.${AWS::Region}.amazoncognito.com