AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  # Define the Lambda Layer for dynamodb_library.py
  DynamoDBLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: DynamoDBHelperLayer
      Description: Layer containing the DynamoDB helper functions
      ContentUri: lambda_function/dynamodb_layer/  # Path to your layer code
      CompatibleRuntimes:
        - python3.9  # Specify the Python version
      LicenseInfo: "MIT"
      
  # First Lambda Function using the Layer
  MyLambdaFunction1:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda_handler_1.lambda_handler
      Runtime: python3.9
      CodeUri: ./lambda_function/
      Environment:
        Variables:
          XSV_CLIENT_TABLE: !Ref XsvClientTable
          XSV_S3_UPLOAD_EVENT_TABLE: !Ref XsvS3UploadEventTable
      Layers:
        - !Ref DynamoDBLayer
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref XsvClientTable
        - DynamoDBCrudPolicy:
            TableName: !Ref XsvS3UploadEventTable

  # Second Lambda Function using the same Layer
  MyLambdaFunction2:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda_handler_2.lambda_handler
      Runtime: python3.9
      CodeUri: ./lambda_function/
      Environment:
        Variables:
          XSV_CLIENT_TABLE: !Ref XsvClientTable
          XSV_S3_UPLOAD_EVENT_TABLE: !Ref XsvS3UploadEventTable
      Layers:
        - !Ref DynamoDBLayer
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref XsvClientTable
        - DynamoDBCrudPolicy:
            TableName: !Ref XsvS3UploadEventTable

  # DynamoDB Tables
  XsvClientTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: xsv_client
      AttributeDefinitions:
        - AttributeName: client_id
          AttributeType: S
      KeySchema:
        - AttributeName: client_id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  XsvS3UploadEventTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: xsv_s3_upload_event_table
      AttributeDefinitions:
        - AttributeName: event_id
          AttributeType: S
      KeySchema:
        - AttributeName: event_id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
