AWSTemplateFormatVersion: '2010-09-09'
Description: EC2 Launch Template, ECS Cluster, and EC2 instance setup for ECS microservices.

Parameters:
  ClusterName:
    Type: String
    Default: MyECSCluster
    Description: Name of the ECS cluster.

  InstanceType:
    Type: String
    Default: t2.micro
    Description: EC2 instance type for the ECS launch template.

  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Name of an existing EC2 KeyPair for SSH access to instances.

Resources:
  # ECS Cluster
  ECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Ref ClusterName

  # IAM Role for ECS Instance
  ECSInstanceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: ECSInstancePolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - ecs:CreateCluster
                  - ecs:DeregisterContainerInstance
                  - ecs:DiscoverPollEndpoint
                  - ecs:Poll
                  - ecs:RegisterContainerInstance
                  - ecs:StartTelemetrySession
                  - ecs:Submit*
                  - ec2:Describe*
                  - ecr:GetAuthorizationToken
                  - ecr:BatchCheckLayerAvailability
                  - ecr:GetDownloadUrlForLayer
                  - ecr:BatchGetImage
                Resource: "*"

  # Instance Profile for ECS Instance Role
  ECSInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref ECSInstanceRole

  # Launch Template for ECS
  ECSLaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName: ECSLaunchTemplate
      LaunchTemplateData:
        InstanceType: !Ref InstanceType
        KeyName: !Ref KeyName
        IamInstanceProfile:
          Name: !Ref ECSInstanceProfile
        UserData:
          Fn::Base64: !Sub |
            #!/bin/bash
            echo ECS_CLUSTER=${ClusterName} >> /etc/ecs/ecs.config
            yum update -y
            yum install -y aws-cli

  # EC2 Instance in ECS
  ECSInstance:
    Type: AWS::EC2::Instance
    Properties:
      LaunchTemplate:
        LaunchTemplateName: !Ref ECSLaunchTemplate
        Version: '$Latest'
      Tags:
        - Key: Name
          Value: ECSInstance

Outputs:
  ClusterName:
    Description: ECS Cluster Name
    Value: !Ref ClusterName

  ECSInstanceId:
    Description: ECS Instance ID
    Value: !Ref ECSInstance
