AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SAM template for Cognito User Pool setup with client credentials and refresh token flow

Parameters:
  UserPoolName:
    Type: String
    Default: MyUserPool
    Description: Name of the Cognito User Pool
  DomainPrefix:
    Type: String
    Default: my-auth-domain
    Description: Prefix for Cognito domain name

Resources:
  CognitoUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Ref UserPoolName
      AdminCreateUserConfig:
        AllowAdminCreateUserOnly: true
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: true
          RequireUppercase: true

  UserPoolDomain:
    Type: AWS::Cognito::UserPoolDomain
    Properties:
      Domain: !Ref DomainPrefix
      UserPoolId: !Ref CognitoUserPool

  UserPoolResourceServer:
    Type: AWS::Cognito::UserPoolResourceServer
    Properties:
      UserPoolId: !Ref CognitoUserPool
      Identifier: "api"
      Name: "MyAPIServer"
      Scopes: 
        - ScopeName: read
          ScopeDescription: "Read access to API"
        - ScopeName: write
          ScopeDescription: "Write access to API"

  UserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    DependsOn: UserPoolResourceServer
    Properties:
      UserPoolId: !Ref CognitoUserPool
      ClientName: app-client
      GenerateSecret: true
      ExplicitAuthFlows:
        - ALLOW_REFRESH_TOKEN_AUTH
      AllowedOAuthFlows:
        - client_credentials
      AllowedOAuthScopes:
        - api/read
        - api/write
      AllowedOAuthFlowsUserPoolClient: true
      PreventUserExistenceErrors: ENABLED
      RefreshTokenValidity: 30    # Refresh token validity in days
      AccessTokenValidity: 1      # Access token validity in hours
      IdTokenValidity: 1          # ID token validity in hours
      TokenValidityUnits:
        AccessToken: "hours"
        IdToken: "hours"
        RefreshToken: "days"

Outputs:
  UserPoolId:
    Description: ID of the Cognito User Pool
    Value: !Ref CognitoUserPool
  UserPoolClientId:
    Description: ID of the Cognito User Pool Client
    Value: !Ref UserPoolClient
  UserPoolDomainName:
    Description: Domain name for the Cognito User Pool
    Value: !Sub ${DomainPrefix}.auth.${AWS::Region}.amazoncognito.com